const categoryStatic = {
  1: { category_name: "产业跟踪", sub_category_name: "生猪", cate_level: 31 },
  2: { category_name: "策略思考", sub_category_name: "每日复盘", cate_level: 11 },
  3: { category_name: "策略思考", sub_category_name: "行业配置", cate_level: 13 }, 
  4: { category_name: "策略思考", sub_category_name: "组合策略", cate_level: 14 },
  5: { category_name: "产业跟踪", sub_category_name: "可选消费", cate_level: 34 },
  6: { category_name: "产业跟踪", sub_category_name: "汽车", cate_level: 33 },
  7: { category_name: "市场跟踪", sub_category_name: "资金流向", cate_level: 22 },
  8: { category_name: "市场跟踪", sub_category_name: "市场情绪", cate_level: 25 },
  9: { category_name: "市场跟踪", sub_category_name: "估值研究", cate_level: 21 },
  10: { category_name: "策略思考", sub_category_name: "周度思考", cate_level: 12 },
  11: { category_name: "市场跟踪", sub_category_name: "大类资产", cate_level: 23 },
  12: { category_name: "产业跟踪", sub_category_name: "投资品", cate_level: 32 },
  13: { category_name: "策略思考", sub_category_name: "模拟组合", cate_level: 15 },
  14: { category_name: "专题报告", sub_category_name: "路演报告", cate_level: 41 },
  15: { category_name: "专题报告", sub_category_name: "专项课题", cate_level: 42 },
  18: { category_name: "市场跟踪", sub_category_name: "数据日报", cate_level: 24 },
  19: { category_name: "产业跟踪", sub_category_name: "货币信用", cate_level: 35 },
  20: { category_name: "市场跟踪", sub_category_name: "宏观高频", cate_level: 24 },
  21: { category_name: "市场跟踪", sub_category_name: "因子收益", cate_level: 26 },
  22: { category_name: "市场跟踪", sub_category_name: "资本品跟踪", cate_level: 27 },
  23: { category_name: "市场跟踪", sub_category_name: "资本品周报", cate_level: 28 },
  24: { category_name: "量化研究", sub_category_name: "股票因子", cate_level: 51 }}

export default categoryStatic